package jp.ac.uryukyu.ie.e245714;

/*
 * This source file was generated by the Gradle 'init' task
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class VendingMachineTest {
   

    @Test
    void selectTest(){
        var drinks = new ArrayList<Drink>();

        Drink cola = new Drink("コーラ",180,5);
        drinks.add(cola);
            
        VendingMachine vendingMachine = new VendingMachine(500);

        vendingMachine.print(drinks);
        
        vendingMachine.select(1,drinks);
        vendingMachine.select(1,drinks);
        vendingMachine.select(1,drinks);
        
        int expectedStock1 = 2;

        assertEquals(expectedStock1,cola.getStock());

    }

    @Test
    void replenishTest(){
        var drinks = new ArrayList<Drink>();

        Drink cola = new Drink("コーラ",180,5);
        drinks.add(cola);
            
        VendingMachine vendingMachine = new VendingMachine(500);

        vendingMachine.print(drinks);

        vendingMachine.replenish(8,1,drinks);

        int expectedStock2 = 13;

        assertEquals(expectedStock2,cola.getStock());
    }
}
